name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t lmrouter .
